### ISSUE TITLE
Removing third side

### ISSUE THREAD

**Issue by Ezcoo** [Spayker/a3wasp-core#3]
Hi,

I'd like to start hosting WASP missions in Arma 3. Only issue I have is the existence of third side. Would you be willing to elaborate what I need to change to remove the third side? Is just reverting the commits with a mention of third side enough?

**Comment by Spayker** [comment]
Hi,

Third side is a part of mission engine. To remove it you need to work closely with mission.sqm file, client, server and config sections.

Commit revert approach is possible here but it also can exclude few important performance related improvements.
