### ISSUE TITLE
Need server keys for @AdWaspLite

### ISSUE THREAD

**Issue by Ezcoo** [Spayker/a3wasp-core#4]
Hi,

I'm sorry for contacting you here but I couldn't think of a better way.

I'm opening a server hosting this mission, but mod @AdWaspLite is missing server keys. Could you add the server keys and update the mod in Steam Workshop?

Thanks in advance,
Ezcoo

**Comment by Spayker** [comment]
Hi,

Unfortunately, no - lack of time. Take pbo file, unpack it and re-create server side keys by BIS tools. Costs you up to 15 minutes.
