### ISSUE TITLE
Mission starts without MHQ - automatic game end after 1 minute

### ISSUE THREAD

**Issue by Czarnyszarf** [Spayker/a3wasp-core#5]
Same as title, I am using the malden version, tried setting parameters like starting distance  The mhq is listed as [destroyed]

![ArmA 3 Screenshot 2022 12 14 - 23 14 14 31](https://user-images.githubusercontent.com/25297827/207726684-c7dda372-a0e4-40ec-b06c-4240b32ca8f6.png)

**Comment by Spayker** [comment]
Check mod list you use on server & hc side

**Comment by Czarnyszarf** [comment]
Well...never mind, headless pc just got damaged 

Is there a way to run mission without headless client?

**Comment by Spayker** [comment]
Short answer: no.
